# Generated by Django 4.1.7 on 2023-05-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(default="NomParDefault", max_length=20)),
                ("maintenanceDate", models.DateTimeField(auto_now_add=True)),
                (
                    "mach",
                    models.CharField(
                        choices=[
                            ("PC", "PC - Run windows"),
                            ("Mac", "Mac - Run MacOS"),
                            (
                                "Serveur",
                                "Serveur - Simple Server to deploy virtual machines",
                            ),
                            ("switch", "Switch - To maintains and connect servers"),
                        ],
                        default="PC",
                        max_length=32,
                    ),
                ),
                ("ip", models.CharField(default="127.0.0.1", max_length=32)),
                (
                    "vlan",
                    models.CharField(
                        choices=[
                            ("Gestion", "77"),
                            ("Clients", "10"),
                            ("Services", "20"),
                        ],
                        default="Aucun",
                        max_length=32,
                    ),
                ),
                ("maj", models.CharField(default="Jamais modifié", max_length=32)),
                ("user", models.CharField(default="Aucun", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=20)),
                ("prenom", models.CharField(max_length=20)),
                (
                    "secteur",
                    models.CharField(
                        choices=[
                            ("Gestion", "77"),
                            ("Clients", "10"),
                            ("Services", "20"),
                        ],
                        default="Gestion",
                        max_length=32,
                    ),
                ),
                ("majU", models.CharField(default="Jamais modifié", max_length=32)),
            ],
        ),
    ]
