# Generated by Django 4.1.7 on 2023-05-04 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(default="None", max_length=6)),
                (
                    "maintenanceDate",
                    models.DateField(
                        default=datetime.datetime(2023, 5, 4, 9, 23, 1, 764476)
                    ),
                ),
                (
                    "match",
                    models.CharField(
                        choices=[
                            ("PC", "PC - Run windows"),
                            ("Mac", "Mac - Run MacOS"),
                            (
                                "Serveur",
                                "Serveur - Simple Server to deploy virtual machines",
                            ),
                            ("switch", "Switch - To maintains and connect servers"),
                        ],
                        default="PC",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=10)),
                ("prenom", models.CharField(max_length=10)),
            ],
        ),
    ]
