# Generated by Django 4.1.7 on 2023-05-09 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 9, 16, 36, 53, 871623)
            ),
        ),
    ]
