# Generated by Django 4.1.7 on 2023-05-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0006_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="maintenanceDate",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="match",
        ),
    ]
