# Generated by Django 4.1.7 on 2023-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0007_remove_machine_maintenancedate_remove_machine_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="id",
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
