# Generated by Django 4.1.7 on 2023-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0008_alter_machine_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="id",
            field=models.CharField(
                editable=False, max_length=4, primary_key=True, serialize=False
            ),
        ),
    ]
