# Generated by Django 4.1.7 on 2023-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0009_alter_machine_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="machine",
            name="nom",
            field=models.CharField(default="NomParDefault", max_length=20),
        ),
    ]
