# Generated by Django 4.1.7 on 2023-05-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0010_alter_machine_id_alter_machine_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="nom",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="prenom",
            field=models.CharField(max_length=20),
        ),
    ]
