# Generated by Django 4.1.7 on 2023-05-19 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0012_machine_maintenancedate_machine_match"),
    ]

    operations = [
        migrations.RenameField(
            model_name="machine",
            old_name="match",
            new_name="mach",
        ),
        migrations.AddField(
            model_name="machine",
            name="ip",
            field=models.CharField(default="127.0.0.1", max_length=32),
        ),
        migrations.AddField(
            model_name="machine",
            name="vlan",
            field=models.CharField(
                choices=[
                    ("VLAN Gestion", "VLAN 77"),
                    ("VLAN Clients", "VLAN 10"),
                    ("VLAN Services", "VLAN 20"),
                ],
                default="VLAN Gestion",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 19, 11, 27, 9, 566472)
            ),
        ),
    ]
