# Generated by Django 4.1.7 on 2023-05-19 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "computerApp",
            "0013_rename_match_machine_mach_machine_ip_machine_vlan_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 19, 11, 29, 59, 461517)
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="vlan",
            field=models.CharField(
                choices=[("Gestion", "77"), ("Clients", "10"), ("Services", "20")],
                default="VLAN Gestion",
                max_length=32,
            ),
        ),
    ]
