# Generated by Django 4.1.7 on 2023-05-19 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0017_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="secteur",
            field=models.CharField(
                choices=[("Gestion", "77"), ("Clients", "10"), ("Services", "20")],
                default="Gestion",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 19, 12, 1, 26, 731722)
            ),
        ),
    ]
