# Generated by Django 4.1.7 on 2023-05-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0026_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
