# Generated by Django 4.1.7 on 2023-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0027_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="maj",
            field=models.CharField(default="Jamais modifié", max_length=32),
        ),
    ]
