# Generated by Django 4.1.7 on 2023-05-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0028_machine_maj"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="user",
            field=models.CharField(default="Aucun", max_length=32),
        ),
    ]
