# Generated by Django 4.1.7 on 2023-05-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0031_alter_machine_utilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="utilisateur",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="computerApp.utilisateur",
            ),
        ),
    ]
