# Generated by Django 4.1.7 on 2023-05-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0032_alter_machine_utilisateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="utilisateur",
        ),
        migrations.AddField(
            model_name="machine",
            name="user",
            field=models.CharField(default="Aucun", max_length=32),
        ),
        migrations.AlterField(
            model_name="machine",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("Mac", "Mac - Run MacOS"),
                    ("Serveur", "Serveur - Simple Server to deploy virtual machines"),
                    ("switch", "Switch - To maintains and connect servers"),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
