# Generated by Django 4.1.7 on 2023-05-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0033_remove_machine_utilisateur_machine_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="vlan",
            field=models.CharField(
                choices=[("Gestion", "77"), ("Clients", "10"), ("Services", "20")],
                default="Aucun",
                max_length=32,
            ),
        ),
    ]
